# Project
version=1.2.0
group_id=net.mysticdrew.journeymapteams


# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
java_version=21
journeymap_min_version=1.21.1-6.0.0-beta.72
journeymap_version_range=[1.21.1-6.0.0-beta.72,)
# Mappings (parchment)
mappings_mc_version=1.21.1
mappings_date=2024.11.17

# NeoForge
neoforge_version=21.1.228
neo_form_version=1.21.1-20240808.144430
neoforge_loader_version_range=[4,)

# Forge
forge_version=52.1.10
forge_loader_version_range=[52,)
forge_version_range=[52,)

# Fabric
fabric_api_version=0.116.7+1.21.1
fabric_loader_version=0.19.2

# JourneyMap API
journeymap_api_version=2.0.0-1.21.1-SNAPSHOT

# Teams mod deps (Argonauts deferred no 1.21.1 release)
ftb_teams_version=2101.1.10
ftb_library_version=2101.1.31
architectury_version=13.0.8

# Mod options
mod_name=JourneyMap-Teams
mod_author=Mysticdrew
mod_id=journeymapteams
license=Apache 2.0
description=Integrates Vanilla Teams and other mod teams into JourneyMap
release_type=release
curseforge_project_id=923833
modrinth_project_id=EV5wjtvP

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
dateFormat=yyyy-MM-dd-HH:mm:ss
