plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeConsumed = true
        canBeResolved = false
    }
    commonResources {
        canBeConsumed = true
        canBeResolved = false
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile)
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile)
}

test {
    useJUnitPlatform()
}

neoForge {
    neoFormVersion = neo_form_version
    addModdingDependenciesTo(sourceSets.test)
}

dependencies {
    compileOnly group: 'info.journeymap', name: 'journeymap-api-common',
            version: "${journeymap_api_version}", changing: true

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    testImplementation group: 'info.journeymap', name: 'journeymap-api-common',
            version: "${journeymap_api_version}", changing: true
    testImplementation "dev.ftb.mods:ftb-teams-neoforge:${ftb_teams_version}"
    testImplementation "dev.ftb.mods:ftb-library-neoforge:${ftb_library_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.mockito:mockito-core:5.20.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.20.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}
