import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-loader'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id "com.modrinth.minotaur" version "2.+"
}

dependencies {
    implementation group: 'info.journeymap', name: 'journeymap-api-neoforge',
            version: "${journeymap_api_version}", changing: true

    implementation "dev.ftb.mods:ftb-teams-neoforge:${ftb_teams_version}"
    implementation "dev.ftb.mods:ftb-library-neoforge:${ftb_library_version}"
}

// Automated upload to CurseForge for the win!
if (!project.hasProperty("curseForgeApiKey")) {
    ext.curseForgeApiKey = project.findProperty("curseforge_api_key") ?: "notset"
}
if (!project.hasProperty("modrinthApiKey")) {
    ext.modrinthApiKey = project.findProperty("modrinth_api_key") ?: "notset"
}

task processDocs(type: Copy) {
    from(file("$rootDir/doc/")) {
        include '*.html'
        expand 'version': project.version,
                'date': new Date().format('yyyy-MM-dd'),
                'mcversion': project.minecraft_version,
                'loaderversion': project.neoforge_version,
                'loadername': "NeoForge"
    }
    into layout.buildDirectory.dir("doc")
}

def publishJar = tasks.named("jar")

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    dependsOn processDocs
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, publishJar)
    mainFile.displayName = "${project.mod_id}-${version}+${project.name}"
    mainFile.releaseType = release_type
    mainFile.addModLoader("NeoForge")
    mainFile.addJavaVersion("Java 25")
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.changelogType = "html"
    mainFile.changelog = file(layout.buildDirectory.dir("doc").get().asFile.path + "/changelog.html")
}

modrinth {
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${version}+${project.name}"
    versionName = "${project.mod_id}-${version}+${project.name}"
    versionType = release_type
    uploadFile = publishJar
    gameVersions = ["${project.minecraft_version}"]
    loaders = ["neoforge"]
    def changelogFile = layout.buildDirectory.dir("doc").get().file("changelog.html").asFile
    changelog = changelogFile.exists() ? changelogFile.text : null
}

neoForge {
    version = neoforge_version
    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            programArgument '--username=TeamCaptDev'
        }
        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}
