name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Publish
        run: >
          /bin/sh ./gradlew
          assemble
          modrinth
          publishCurseForge
          -Pmodrinth_api_key=${{ secrets.MODRINTH_KEY }}
          -Pcurseforge_api_key=${{ secrets.CURSEFORGE_KEY }}
          --stacktrace
          -x test
